### ISSUE TITLE
Support for .NET 4.0?

### ISSUE THREAD

**Issue by picrap** [avatar29A/MusicBrainz#15]
Hi,

is it possible to support the .NET framework 4.0? (optionnally client profile is better).

Thanks.

**Comment by avatar29A** [comment]
I think, that impossible. We active use async \ await features and .NET 4.0 not supported it.

**Comment by picrap** [comment]
Yes, I've seen this after submitting the issue. I guess I'll have to upgrade my solutions :wink:

**Comment by avatar29A** [comment]
Ok :+1: I'm closing issue.
