### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by pdwetz** [avatar29A/MusicBrainz#17]
Since the MusicBrainz service throttles based on user agent, that header value should be a custom value per application that utilizes the API. Otherwise, different and otherwise unrelated apps/users could cause others to be throttled. I have a pretty simple pull request I can send that addresses it, with logic confirmed with Fiddler2 in local use; not sure the proper automated test that would address it.

**Comment by avatar29A** [comment]
Add new property in Configuration.cs.

to change UserAgent write:

Configuration.UserAgent = "Chrome/41.0.2228.0";
