### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by acastaner** [avatar29A/MusicBrainz#19]
I see several NuGet packages pointing to this page, which one is the "official" one?

https://www.nuget.org/packages/MusicBrainzWebService/
https://www.nuget.org/packages/MusicBrainzAPI/
https://www.nuget.org/packages/MusicBrainzWebService.PCL/

**Comment by avatar29A** [comment]
Hi.  https://www.nuget.org/packages/MusicBrainzAPI/ is mine. Another projects and mine are not official.
