### ISSUE TITLE
CoverArtArchive always null

### ISSUE THREAD

**Issue by coczero** [avatar29A/MusicBrainz#27]
For every release I search, the CoverArtArchive is null.
This was not the case with the nuget version, but I can't use that one because ReleaseGroups.SearchAsync does not exist in that version...

**Comment by wo80** [comment]
I don't think the XML returned from a release search contains the coverart information. Just take a look at the link in the test case: [ReleaseListTests.cs](https://github.com/avatar29A/MusicBrainz/blob/master/Hqub.MusicBrainz/Hqub.MusicBrainz.API.Test/ReleaseListTests.cs#L9)
