### ISSUE TITLE
Parameters with query

### ISSUE THREAD

**Issue by ColorTwist** [avatar29A/MusicBrainz#31]
Is there a sample of how to use parameters with query? and which parameters are available. 

Another thing, related or not:
For example:
` var art= await Artist.GetAsync(id);`

This will return artist information which is great, but I noticed many fields are return empty like
Relations = null
Rating = null
Score = 0 
etc..

I am looking for a way to receive also additional data like band members (relations, score) if i provide for example- backstreet boys mbid?

**Comment by wo80** [comment]
1) There's only the base `Relation` class, so specialized relations like `artist-rels` or `url-rels` are not available at the moment.
2) The `Score` value will only be set for search requests.
3) If any other properties are null, this usally means that they were not available in the server response.
4) If you want to include additional information in a `Get` request, use the `inc` parameter, for example
```c#
Artist.GetAsync(mbid, "release-groups", "tags", "works");
```
5) If you want to setup the parameters for a `Search` request, you can use the `QueryParameters` class, see [QueryParametersTests.cs](https://github.com/avatar29A/MusicBrainz/blob/master/Hqub.MusicBrainz/Hqub.MusicBrainz.API.Test/QueryParametersTests.cs).

**Comment by ColorTwist** [comment]
I see, great!

Hope to see Relation implemented.
Where can i find Tag list supported?
I found https://picard.musicbrainz.org/docs/tags/
However, it seems i need a different tag list.

**Comment by wo80** [comment]
A tag is just a string, and most Musicbrainz entities will have a list of tags associated to them. Picard is a tool for tagging audio files (i.e. MP3 tags). Two different things ...

**Comment by ColorTwist** [comment]
For me "members" and  "original members"  are important as it shows the member names of groups (bands).
Other information/images links resources for the singers/band. Like Wikipedia link, BBC music link, etc..
Not sure how important is that.

**Comment by ColorTwist** [comment]
Not related, but suggestion to add: GetTopAlbumsByMbidAsync

**Comment by wo80** [comment]
Ok, to get members and related websites you can now do
```c#
var mbid = "ca891d65-d9b0-4258-89f7-e6ba29d83767"; // Iron Maiden

var artist = await Artist.GetAsync(mbid, "artist-rels", "url-rels");
            
Console.WriteLine("{0} members:", artist.Name);

// To filter relations, inspect "TargetType" and "Type" properties of relation.
foreach (var relation in artist.Relations.Where(r => r.TargetType == "artist" && r.Type.Contains("member")))
{
    Console.WriteLine("{0}: {1} ({2} - {3})", relation.Artist.Name, string.Join(" / ", relation.Attributes),
        relation.Begin, relation.End);
}

Console.WriteLine("{0} related websites:", artist.Name);

foreach (var relation in artist.Relations.Where(r => r.TargetType == "url"))
{
    Console.WriteLine("{0}: {1}", relation.Type, relation.Url.Resource);
}
```
If you'd like to play around with the code - until this PR gets merged - you can checkout my fork https://github.com/wo80/MusicBrainz.

**Comment by ColorTwist** [comment]
I checked, it's working!
Thanks, I really appreciate it!
