### ISSUE TITLE
Portable vs .NET Standard

### ISSUE THREAD

**Issue by wo80** [avatar29A/MusicBrainz#35]
I was wondering if the portable project is still needed? It could be replaced by a .NET Standard 2.0 project.

There are a couple of files in the portable project though, where I'm not sure why they were added (like ImageLoader, MyHttpClient, ReadableException). I think, they should be removed and we just see if anybody wants them back.

**Comment by wo80** [comment]
Portable class libraries were a first approach to open .NET to other platforms/devices (like Windows Phone - there never was a full .NET framework for Windows Phone).

The whole idea of portable projects was indeed confusing and is now replaced by the .NET Standard (which is a good thing imho).

More info: https://stackoverflow.com/questions/5238955/what-is-a-portable-class-library

**Comment by ColorTwist** [comment]
From what i read it .NET Standard 2.0 is the way to go. Like you said.

**Comment by ColorTwist** [comment]
It is evolving,  final stages of being released 2.1 core.
https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1/?utm_source=vs_developer_news&utm_medium=referral

**Comment by wo80** [comment]
Here's one problem I see:
Portable class libraries are supported since VS2010, while support for .NET Standard projects is only there since VS2017.

If this isn't a problem, then the whole solution could be re-organized:
http://markheath.net/post/supporting-net-standard-and-net-35
https://docs.microsoft.com/en-us/dotnet/core/porting/

This would also simplify the creation of the nuget package.

**Comment by ColorTwist** [comment]
Personally i use VS2017.
VS2017 is available from March 2017. I guess many have updated.
