### ISSUE TITLE
Getting artists by tag

### ISSUE THREAD

**Issue by ColorTwist** [avatar29A/MusicBrainz#37]
I am trying to get artists by tag:
like: https://beta.musicbrainz.org/tag/pop/artist
Trying to get popular artists by tag, and this seems the only way with MusicBrainz.
Can this be done with the c# implementation of the api?

**Comment by wo80** [comment]
I not sure this can be done with the webservice. Obviously, you could do
```c#
var artists = await Artist.SearchAsync("tag:pop");
// http://musicbrainz.org/ws/2/artist/?query=tag:pop&fmt=json
```
but this does not return the list as presented on https://beta.musicbrainz.org/tag/pop/artist (which seems to be sorted by some kind of 'relevance').

**Comment by ColorTwist** [comment]
I get you.

All these different possibilities with Browse, search or Get is confusing.
3 different methods to get different data.
I know that is how MusicBrainz works, i guess it's just learning curve.

**Comment by ColorTwist** [comment]
For example, trying to do:
http://beta.musicbrainz.org/ws/2/release-group/a1084754-8bb5-3ebc-bbd2-6a27d48e798a?inc=ratings+releases

I wrote 
   var artistTracks = await ReleaseGroup.BrowseAsync("", AlbumMbid, 20, 0, "ratings","releases");
something is wrong with the query string.

**Comment by ColorTwist** [comment]
I guess after i get  into it more i can assist in documentation.

**Comment by ColorTwist** [comment]
i did try
 await ReleaseGroup.BrowseAsync("artist", AlbumMbid, 20, 0, "ratings","releases");
but i get exception .

**Comment by wo80** [comment]
Take a look at https://wiki.musicbrainz.org/Development/XML_Web_Service/Version_2#Browse

Browsing release-groups does not support including "releases".

At the moment, the exceptions thrown when the webservice fails are not instructive at all. If you look at the response of request, corresponding to the C# code

http://musicbrainz.org/ws/2/release-group?artist=45a663b5-b1cb-4a91-bff6-2bef7bbfdd76&limit=20&offset=0&inc=ratings+releases&fmt=json
```
error: "releases is not a valid inc parameter for the release-group resource."
```
you can see the problem. This error message should be included in the exception thrown, so:

please leave this issue open until it gets addressed :-)

**Comment by ColorTwist** [comment]
Sure,

I want to elaborate what i am trying to do and if it is possible:
First i get artist main albums:
ReleaseGroup.BrowseAsync("artist", artistMbid, limit, 0, "ratings");

I save aside the release group mbid,

Now i want to get the tracks of only one (main one preferable)  of that release group, this i where i am stuck. :)

Regarding errors, just a suggestion, to show what MusicBrainz returns as error.

**Comment by wo80** [comment]
Just chain a couple of requests:
1. Browse release-groups: `ReleaseGroup.BrowseAsync("artist", artist_id, ...)`.
2. Get mbid of release-group you are interested in (don't know what you mean by _main one preferable_).
3. Get details of release-group: `ReleaseGroup.GetAsync(group_id, "artists", "releases")`.
4. Get mbid of release you are interested in.
5. Get details of release: `Release.GetAsync(release_id, "recordings")`.

**Comment by ColorTwist** [comment]
Great, will check that out.

Regarding  "main one", since there are many releases per release group, i need only to feach 1 release from the group. Question is, which 1 to fetch?  maybe first country that released it.

**Comment by wo80** [comment]
Yeah, I usually do something like
```c#
var release = releases.Items
    .Where(r => r.Date != null)
    .OrderBy(r => r.Date)
    .First();
```

**Comment by ColorTwist** [comment]
That's great, i appreciate that.

**Comment by ColorTwist** [comment]
error: "releases is not a valid inc parameter for the release-group resource."
fixed, now it shows the error.
