### ISSUE TITLE
Error with Release.GetAsync on a specific album mbid

### ISSUE THREAD

**Issue by ColorTwist** [avatar29A/MusicBrainz#39]
When executing : 
`   var a = await Release.GetAsync("019a762a-ef46-3dc6-aaca-ff5afc358ef2", "artists", "recordings", "ratings");`
Url in which it executes:
http://beta.musicbrainz.org/ws/2/release/019a762a-ef46-3dc6-aaca-ff5afc358ef2/?inc=artists+recordings+ratings&fmt=json
I get the following error:

> System.Runtime.Serialization.SerializationException: 'ValueType 'System.Int32' cannot be null.'

**Comment by wo80** [comment]
This is because track.Length should be nullable. I think it's already fixed in my `examples` branch. Could you verify?

**Comment by ColorTwist** [comment]
You right, it is fixed now,
however, it happen with: 
http://musicbrainz.org/ws/2/release/6d542715-f6df-43d6-bce0-f9d0f3c90fd1/?inc=artists+recordings+ratings&fmt=json
same function, different album mbid

**Comment by wo80** [comment]
So at last: recording.Length should be nullable.

The default JSON deserializer can be annoying at times ...

**Comment by ColorTwist** [comment]
Correct, it fixed it. 
Not sure how you find errors with the JSON deserializer as it's a closed dll :)
Leaving this open until updated.
