### ISSUE TITLE
[Question] Is there a way to hold local metadata in sync?

### ISSUE THREAD

**Issue by philippk80** [avatar29A/MusicBrainz#40]
Hello,

great work with the library here!
I have the requirement to cache metadata local and refresh it when there are some changes.
I don't found anything on musicbrainz site to achieve something like that. (Webhooks, etc)
I have to do polling or not? That's hard work with 1 request per second :'D

Thanks.

**Comment by avatar29A** [comment]
As I know. There is only one official way https://musicbrainz.org/doc/Live_Data_Feed, but it costs money. 

Also, you may see this project: https://github.com/lalinsky/mbslave, might be is will be useful to you.

**Comment by philippk80** [comment]
Okay then I have to write an refresh method. I don't want to replicate the whole database.
