### ISSUE TITLE
Get by type of albums with ReleaseGroup.BrowseAsync

### ISSUE THREAD

**Issue by ColorTwist** [avatar29A/MusicBrainz#46]
Hello,

Is it possible to use ReleaseGroup.BrowseAsync("artist", artistMbid, 50, 0, "ratings");
but get only albums and singles like stated in MusicBrainz api docs:
Like:
 /ws/2/release-group?artist=410c9baf-5469-44f6-9852-826524b80c61&type=album|single

**Comment by wo80** [comment]
There's an overload allowing you to specify a type, but at the moment it will throw if you use the pipe symbol to specify more than one type. This is bug and will be fixed. Until then:
```c#
var mbid = "410c9baf-5469-44f6-9852-826524b80c61";
var albums = ReleaseGroup.BrowseAsync("artist", mbid, "album", 50, 0, "ratings");
var singles = ReleaseGroup.BrowseAsync("artist", mbid, "single", 50, 0, "ratings");
```

**Comment by ColorTwist** [comment]
Thanks for the info, appreciate your great work.
I had to push the latest repository as I see this overload is pretty new.
It seems to be working, thanks!
Would be nice to be able to use pipe symbol or parameters for 'type' in the future to save 1 call :)

**Comment by ColorTwist** [comment]
i'll note that using`  ReleaseGroup.BrowseAsync("artist", mbid, "album", 50, 0, "ratings");` also returns any secondary type that is related to `album`, like `Album + Compilation , Album + Live,` etc..
From MusicBrainz API it seems it's not possible to get only albums as a primary type without secondary type. 
Am I correct on this consumption?

**Comment by wo80** [comment]
Yes, at least I don't know of any way to filter browse request by secondary types.
