### ISSUE TITLE
Get releases by release group id

### ISSUE THREAD

**Issue by ColorTwist** [avatar29A/MusicBrainz#47]
Question,
I am using the following to get releases of a release group using:
` ReleaseGroup releaseGroupList =`ReleaseGroup.GetAsync(releaseGroup.Id, "artists", "releases");``
and then uses `releaseGroupList.Releases` with LINQ to get `Offical` status,
Is there a more elegant way to do a method?

**Comment by wo80** [comment]
Try this:
```c#
var query = new QueryParameters<Release>()
{
    { "rgid", releaseGroupId }
};

var releases = Release.SearchAsync(query);
// or
// var releases = Release.SearchAsync("rgid:" + releaseGroupId);
```
You can find out more about available search fields in the [MusicBrainz search documentation](https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2/Search#Release).

**Comment by ColorTwist** [comment]
Thanks
