### ISSUE TITLE
2 calls hang

### ISSUE THREAD

**Issue by fededim** [avatar29A/MusicBrainz#49]
Hi,

I am trying to use your library (through nuget package latest version). I tried 2 calls but they both hang looping forever (stopped after 1 minute):

var recs = Recording.Search("the right thing");
var art=Artist.Search("Jovanotti");

I also tried the Async method, but I get the same results. Using fiddler it does not record any network traffic. Do you have any guess ?

**Comment by wo80** [comment]
Do not call the sync methods from a gui thread. If possible, use the async methods.

What kind of app are you writing (console, winforms, wpf ...)? When trying the async methods, did you use the async-await pattern?

**Comment by fededim** [comment]
Winforms. Ok I was using .Result and not await and async, sorry I close the issue.
