### ISSUE TITLE
Project changes

### ISSUE THREAD

**Issue by wo80** [avatar29A/MusicBrainz#5]
In my fork I'd like to change a couple of things and I'd like to know if I should add pull requests for all of them:

1) As mentioned in issue #3, fixing the non-serialized list elements will affect a few places. I haven't compared with @deepakyadav project, but I guess it will be pretty similar.
2) Rename the namespace form ```Hqub.MusicBrainze.API``` to ```Hqub.MusicBrainz```.
3) Rename ```APIGlobalSettings``` to ```Configuration``` and maybe add a few more options as static properties (e.g. web proxy).
4) Remove url configuration from Settings.settings and add string constants to WebRequestHelper.cs.
5) Translate any russian descriptions to english.
6) Remove Constants.resx from Localization folder.

Let me know what you think, and I'll start making the pull requests.

**Comment by avatar29A** [comment]
1,2,3,5 - good.  :+1:  
4, 6 - Explain please motivation?

**Comment by wo80** [comment]
4) Since the urls don't change and aren't supposed to be user configurable, they are perfect candidates for constants.

6) The values in the Constants.resx file are not localizable - they are just constants. The "Artist" value is only used in the ```Artist``` class, so why not just write
```c#
WebRequestHelper.CreateLookupUrl("artist", id, CreateIncludeQuery(inc))
```
instead of
```c#
WebRequestHelper.CreateLookupUrl(Localization.Constants.Artist, id, CreateIncludeQuery(inc))
```
The same holds for the other entries (well, some of them aren't even used (Label, Tag)).

**Comment by avatar29A** [comment]
4. Ok, may be.

5. I do not like to use string literals directly. What if Constant.resx replace on MusicBrainzConstants.cs or something like that ?

**Comment by wo80** [comment]
Ok. But I think we shouldn't add another class for those constants. What about adding them to the associated class. So ```Artist``` class would look something like
```c#
public class Artist : Entity
{
    private string const EntityName = "artist";

    // ...
    public async static Task<Artist> GetAsync(string id, params string[] inc)
    {
        return await GetAsync<Artist>(id, WebRequestHelper.CreateLookupUrl(EntityName, id, CreateIncludeQuery(inc)));
    }
    // ...
}
```
Same for the other affected classes.

**Comment by avatar29A** [comment]
Ok, good :+1:

**Comment by wo80** [comment]
The latest commits still have the namespace ```Hqub.MusicBrainz.API```. Do you want to keep the ```API``` suffix, or should it be dropped?

**Comment by deepakyadav** [comment]
@wo80 Have you fixed task 1?
I am working on creating a new project in this solution by reusing as many files as possible. If you have not done/started, then I can fix this. So I will be able to reuse files.

**Comment by wo80** [comment]
@deepakyadav I haven't started yet.
