### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by wo80** [avatar29A/MusicBrainz#54]
@avatar29A Could you please check if anything needs to be done for migrating from travis-ci.org to travis-ci.com.

I pushed some updates to the `fluent` branch and the travis build keeps hanging in queued state.

See https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository.

Same applies to the LastFm project.

Thanks!

**Comment by wo80** [comment]
Ok, so ci just needed some time. Still, if you find the time, you might want to check if there's something to do regarding migration.

**Comment by avatar29A** [comment]
Hi. I have done migration to travis-ci.com. Looks working.

https://travis-ci.com/github/avatar29A/MusicBrainz

https://github.com/avatar29A/MusicBrainz/pull/55
