### ISSUE TITLE
Can't fetch any data on AspNet Core Blazor WASM

### ISSUE THREAD

**Issue by arsinclair** [avatar29A/MusicBrainz#58]
I'm trying to use the nuget package in my Blazor WASM project. When the following code is executed
```cs
using (var client = new MusicBrainzClient()) {
    release = await client.Releases.GetAsync(id, "genres");
}
```
I get an exception:

> System.PlatformNotSupportedException: Operation is not supported on this platform.
at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
at Hqub.MusicBrainz.API.MusicBrainzClient.CreateHttpClient(Uri baseAddress, Boolean automaticDecompression, IWebProxy proxy) 
at Hqub.MusicBrainz.API.MusicBrainzClient..ctor(String baseAddress, IWebProxy proxy)
at Hqub.MusicBrainz.API.MusicBrainzClient..ctor()
at WASM.Pages.Poster.ProcessRelease(String id)
at WASM.Pages.Poster.FileUploadedCallback(FlacFile file)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.ThreadPool.Callback()

As we can see in the trace, the exception originates here https://github.com/avatar29A/MusicBrainz/blob/882a1b7fdc57791fd27cfc2343e383205e5ceac7/Hqub.MusicBrainz/Hqub.MusicBrainz.API/MusicBrainzClient.cs#L182

It is caused by the `handler.AutomaticDecompression` field setter throwing a System.PlatformNotSupportedException exception, when it is called. This behavior is explained here https://stackoverflow.com/a/52526415/6184866. It looks like `HttpClientHandler` is being removed from Blazor, since it is not functional in a Web Assembly.

**Comment by arsinclair** [comment]
I can see two solutions: either allow the user to provide its own HttpClient implementation
```cs
public MusicBrainzClient(string baseAddress, IWebProxy proxy, HttpClient httpClient)
{
    var urlBuilder = new UrlBuilder(true);

    Artists = new ArtistService(this, urlBuilder);
    Recordings = new RecordingService(this, urlBuilder);
    Releases = new ReleaseService(this, urlBuilder);
    ReleaseGroups = new ReleaseGroupService(this, urlBuilder);
    Work = new WorkService(this, urlBuilder);

    client = httpClient ?? CreateHttpClient(new Uri(baseAddress), true, proxy);
    client.BaseAddress = new Uri(baseAddress);
}
```
or don't use `HttpClientHandler`
```cs
private HttpClient CreateHttpClient(Uri baseAddress)
{
    return new HttpClient() {
        DefaultRequestHeaders.Add("User-Agent", UserAgent);
        BaseAddress = baseAddress;
    };
}
```
By the way, what is the purpose of `HttpClientHandler` here? Is it just to be able to use proxy?

**Comment by wo80** [comment]
> By the way, what is the purpose of `HttpClientHandler` here? Is it just to be able to use proxy?

Well, using `HttpClient` I thought `HttpClientHandler` was the way to setup some advanced aspects like proxies.

I guess there are two options now:
1. Add a special factory method, something like
```c#
public static MusicBrainzClient CreateWasmClient(...);
```
2. Use `HttpWebRequest` instead of `HttpClient` and set up proxy and compression headers there.

I haven't used Blazor yet, so please test whatever solution you prefer. A pull request would be welcome.

**Comment by wo80** [comment]
**Additional note:**

At first I discarded you proposition of adding a separate constuctor
```c#
public MusicBrainzClient(string baseAddress, IWebProxy proxy, HttpClient httpClient)
```
since I like to keep the number of separate constructors (with multiple arguments) as low as possible, but in this case, only one additional constructor would be neccessary:
```c#
public MusicBrainzClient(HttpClient httpClient)
```
Additionally, the proxy setup could be propagated through a public property (forwarded to HttpClient.DefaultProxy).

**Comment by arsinclair** [comment]
@wo80 Sorry I wasn't able to find time to look into it yet. At a glance, these are all good suggestions. I will take a closer look, hopefully, tomorrow.

**Comment by arsinclair** [comment]
In case anyone is wondering now how to make it work in blazor, here's how I do it. In `Program.cs` register scoped MusicBrainzService:

```cs
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    ...

    builder.Services.AddScoped(x => new MusicBrainzClient(CreateMusicBrainzHttpClient()));

    ...
    await builder.Build().RunAsync();
}

private static HttpClient CreateMusicBrainzHttpClient()
{
    HttpClient client = new HttpClient();
    client.BaseAddress = new Uri("https://musicbrainz.org/ws/2/");
    client.DefaultRequestHeaders.UserAgent.Add(new System.Net.Http.Headers.ProductInfoHeaderValue("Hqub.MusicBrainz", "3.0-beta"));
    client.DefaultRequestHeaders.UserAgent.Add(new System.Net.Http.Headers.ProductInfoHeaderValue("+(https://github.com/avatar29A/MusicBrainz)"));
    return client;
}
```

and then in your actual `.razor` file you need to inject it before it can be used:

```razor
@inject MusicBrainzClient musicBrainzClient

...

@code {
    private async Task GetRelease(string id)
    {
        release = await musicBrainzClient.Releases.GetAsync(id);

        ...
    }
}
```
