### ISSUE TITLE
How to get track artist please?

### ISSUE THREAD

**Issue by HomerJau** [avatar29A/MusicBrainz#61]
Hi,

I hope someone can help me. I need to get the track artist for all tracks in a various Artist releases.

I'm using this call below to get data for a specific release. (works fine):

Client.Releases.GetAsync(pID, "recordings", "media", "release-groups", "genres")

This gives the media and media tracks (titles, TrackNo etc) but the Track.Recording does not have Credits.

Can you show me how to fetch Credits for all tracks in a release or media please. (I want the track artist)

THX

**Comment by wo80** [comment]
Adding `artist-credits` to the `inc` params should give you the credits for all tracks:

```c#
var release = await client.Releases.GetAsync("7a7b7bb2-5abe-3088-9e3e-6bfd54035138",
    "recordings",
    "artist-credits");
```
Corresponding url:
https://musicbrainz.org/ws/2/release/7a7b7bb2-5abe-3088-9e3e-6bfd54035138/?inc=recordings+artist-credits

**Comment by HomerJau** [comment]
Thanks You!

I confirm this returns the track artist.

I really appreciate your fast response. Thanks again.
