### ISSUE TITLE
Increasing the accuracy of the searches

### ISSUE THREAD

**Issue by fergalmoran** [avatar29A/MusicBrainz#62]
Hello all, thanks for this lovely library. After playing with it for a day I've found you can increase the accuracy of the results by changing all instances of WebUtility.UrlEncode to Uri.EscapeDataString

Here's an example, this library fails to find the correct result for Conflict - The Serenade is Dead, but if you make that change it finds it. Here are the different URLs that are produced so you can see what's happening.

First with WebUtility.UrlEncode
```
https://musicbrainz.org/ws/2/release?query=title%253AThe%2520Serenade%2520Is%2520Dead%2520AND%2520artist%253AConflict&limit=25&offset=0&fmt=json
```

Next with Uri.EscapeDataString
```
https://musicbrainz.org/ws/2/release?query=title%3AThe%20Serenade%20Is%20Dead%20AND%20artist%3AConflict&limit=25&offset=0&fmt=json 
```

The main difference seems to be how WebUtility.UrlEncode escapes the colons with %253 rather than %3A although the spaces look off also.
Anyway, thought I'd let you know and I'm happy to spin up a PR for you if you want.

**Comment by wo80** [comment]
That's strange: `%25` is the encoded percent character, so the encoded url got encoded a second time (`%20` -> `%2520`, `%3A` -> `%253A`), which shouldn't be the case for both `WebUtility.UrlEncode` and `Uri.EscapeDataString`. Here's a summary of the main differences:
https://stackoverflow.com/questions/602642/server-urlencode-vs-httputility-urlencode/47877559#47877559

I will take a closer look tomorrow and report back.

**Comment by wo80** [comment]
Can you please give a minimal code example that leads to the problem? I cannot reproduce this.

The change from `Uri.EscapeDataString` to `WebUtility.UrlEncode` was made intentionally, but if you look at the discussion, you can see that I wasn't too confident about the change: https://github.com/avatar29A/MusicBrainz/pull/50

**Comment by fergalmoran** [comment]
> EDIT: Are you sure you didn't pass an already encoded query string to `client.Recordings.SearchAsync(query)`?
🤦 Yup... that appears to be exactly what I did! Sorry to waste your time!
