### ISSUE TITLE
QueryParameters() is returning a badly formatted string

### ISSUE THREAD

**Issue by davezeetone** [avatar29A/MusicBrainz#64]
I am using your example 3 and have noticed an issue with:

`var query = new QueryParameters<ReleaseGroup>()
            {
                { "artist", band },
                { "releasegroup", album },
                { "type", "album" },
                { "status", "official" }
            };`

it is returning where it should be '%20AND%20' it is returning +AND+

my requestmessage: {https://musicbrainz.org/ws/2/release-group?query=artist%3A"Pink+Floyed"+AND+releasegroup%3A"Wish+You+Were+Here"+AND+type%3Aalbum+AND+status%3Aofficial&limit=25&offset=0&fmt=json}

which of course results in ) results found :(

**Comment by wo80** [comment]
Never heard a Pink Floyed song. But I can recommend Pink Floyd ;-)

**Comment by davezeetone** [comment]
Sorry just got it working, I had to encode the band and album strings before adding to the query. sorry to bother you.

**Comment by wo80** [comment]
No worries! I suspected the wrong spelling being the cause of this issue.
